.PHONY: clean All

All:
	@echo "----------Building project:[ Tasks -  ]----------"
	@cd "Tasks" && "$(MAKE)" -f  "Tasks.mk"
clean:
	@echo "----------Cleaning project:[ Tasks -  ]----------"
	@cd "Tasks" && "$(MAKE)" -f  "Tasks.mk" clean
