.PHONY: clean All

All:
	@echo "----------Building project:[ IR_Send_Controller - Debug ]----------"
	@cd "IR_Send_Controller" && "$(MAKE)" -f  "IR_Send_Controller.mk"
clean:
	@echo "----------Cleaning project:[ IR_Send_Controller - Debug ]----------"
	@cd "IR_Send_Controller" && "$(MAKE)" -f  "IR_Send_Controller.mk" clean
